### ISSUE TITLE
Unexpected inner class format when downloading James 1:7,8

### ISSUE THREAD

**Issue by Shhwip** [woodywood117/bgate#2]
James chapter 1 verse 7 and 8 in the NRSVUE were combined which means that one verse has two references. Annoying. See [here](https://www.biblegateway.com/passage/?search=James%201:7&version=NRSVUE). The value of `csplit` is `[Jas 1 7 Jas 1 8]` which triggers your Unexpected inner class format and exits.
I removed the `os.Exit(1)` from that check and it writes it as James 1:7 and skips over verse 8. Not the worst implementation. 
`9|James|1|7|1|For the doubter, being double-minded and unstable in every way, must not expect to receive anything from the Lord.|`
`10|James|1|9|1|Let the brother or sister of humble means boast in having a high position |Poverty and Riches
`

Consider adding a `strconv.Atoi(csplit[4]) && strconv.Atoi(csplit[5])` check to see if its a double verse issue and if so don't exit

**Comment by NilPtrDeref** [comment]
Thanks for the submission, took a look and you're right. It did have an issue with parsing double verses. This should be fixed by #3.

**Comment by NilPtrDeref** [comment]
I chose to just validate that it had at least 3 fields. That way it should work for any number of grouped verses.
